server:
  port: 8080

spring:
  config:
    import: optional:ai.yml
  jmx:
    enabled: false 
  datasource:
    url: jdbc:mysql://localhost:3306/jetrace?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 

mybatis:
  configuration:
    map-underscore-to-camel-case: true